--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/EconomyPE
build-by-default: true
branches:
- main
projects:
  EconomyPE:
    path: ""
    libs:
      libasynql:
        src: poggit/libasynql/libasynql
        version: ^4.1.1
        branch: pm5
...
