name: EconomyPE
version: 1.0.0
author: Terpz710
api: 5.0.0
main: Terpz710\EconomyPE\Money
description: Adds economy support

permissions:
  economype.pay:
    description: Allows the user to pay another user.
    default: true
  economype.mymoney:
    description: Allows the user to see their balance.
    default: true
  economype.seemoney:
    description: Allows the user to see another users balance.
    default: true
  economype.addmoney:
    description: Allows the user to add money to another user balance.
    default: op
  economype.removemoney:
    description: Allows the op-user to remove another user balance.
    default: op
  economype.topmoney:
    description: Allows the user to see the top balances.
    default: true
  economype.setmoney:
    description: Allows the op-user to set another user balance.
    default: op